version: '3'

services:
    backend:
        build: ./server
        ports: 
          - 5000:5000
        restart: unless-stopped

    frontend: 
        build: ./client
        ports:  
          - 8080:8080 
        restart: unless-stopped
        depends_on: 
          - backend
    
    # mongo:
    #     image: mongo
    #     restart: always
    #     environment:
    #       MONGO_INITDB_ROOT_USERNAME: root
    #       MONGO_INITDB_ROOT_PASSWORD: password
    #     volumes:
    #       - ./mongo:/docker-entrypoint-initdb.d



